### ISSUE TITLE
Color palette

### ISSUE THREAD

**Issue by alcb1310** [chingu-voyages/v41-geckos-team-08#26]

**Comment by HectorAgudelo** [comment]
[ratingMockup](https://dribbble.com/shots/14448812-Little-Funny-Rating-Interaction-Babyfood-Website-UI?utm_source=Clipboard_Shot&utm_campaign=katkather&utm_content=Little%20%26%C2%A0Funny%20Rating%20Interaction%20-%20Babyfood%20Website%20UI&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=katkather&utm_content=Little%20%26%C2%A0Funny%20Rating%20Interaction%20-%20Babyfood%20Website%20UI&utm_medium=Social_Share)
